const demoSource =
    {
        "id": 5,
        "name": "第一版主网",
        "baseUrl": "https://www.bzbz1024.com/",
        "headers": null,
        "enabled": true,
        "ruleType": "xpath",
        "ruleGroups": {
            "basic": [{
                "key": "charset",
                "label": "页面编码",
                "placeholder": "utf-8",
                "id": "rule-1762074820001-37",
                "value": ""
            }, {
                "key": "headers",
                "label": "自定义请求头",
                "placeholder": "User-Agent: ...",
                "description": "以 JSON 格式书写",
                "id": "rule-1762074820001-38",
                "value": "{\"user-agent\":\"Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1 Edg/141.0.0.0\"}\r\n"
            }],
            "search": [{
                "key": "searchUrl",
                "label": "搜索地址",
                "placeholder": "https://example.com/search?q={{key}}",
                "id": "rule-1762074820001-39",
                "value": "https://www.bzbz1024.com/search/?keyword={{key}}"
            }, {
                "key": "itemSelector",
                "label": "搜索列表规则",
                "placeholder": ".result-item",
                "id": "rule-1762074820001-40",
                "value": "//div[contains(@class, 'search-card')]"
            }, {
                "key": "titleSelector",
                "label": "书名规则",
                "placeholder": ".title",
                "id": "rule-1762074820001-41",
                "value": "/div[1]/span[1]/a/text()"
            }, {
                "key": "authorSelector",
                "label": "作者规则",
                "placeholder": ".author",
                "id": "rule-1762074820001-42",
                "value": "/div[1]/span[2]/a/text()"
            }, {
                "key": "categorySelector",
                "label": "分类规则",
                "placeholder": ".category",
                "id": "rule-1762074820001-43",
                "value": ""
            }, {
                "key": "introSelector",
                "label": "简介规则",
                "placeholder": ".intro",
                "id": "rule-1762074820001-44",
                "value": "/div[2]/text()"
            }, {
                "key": "coverSelector",
                "label": "封面规则",
                "placeholder": ".cover",
                "id": "rule-1762074820001-45",
                "value": ""
            }, {
                "key": "detailSelector",
                "label": "详情页地址规则",
                "placeholder": ".detail-url",
                "id": "rule-1762074820001-46",
                "value": "/div[1]/span[1]/a/@href"
            }, {
                "key": "nextPage",
                "label": "翻页规则",
                "placeholder": "a.next",
                "id": "rule-1762074820001-47",
                "value": ""
            }],
            "discover": [{
                "key": "channels",
                "label": "发现配置规则",
                "placeholder": "[{\"title\":\"玄幻\",\"url\":\"/xuanhuan\"}]",
                "id": "rule-1762074820001-48",
                "value": ""
            }, {
                "key": "itemSelector",
                "label": "列表项规则",
                "placeholder": ".book-item",
                "id": "rule-1762074820001-49",
                "value": ""
            }, {
                "key": "titleSelector",
                "label": "书名规则",
                "placeholder": ".book-title",
                "id": "rule-1762074820001-50",
                "value": ""
            }, {
                "key": "authorSelector",
                "label": "作者规则",
                "placeholder": ".author",
                "id": "rule-1762074820001-51",
                "value": ""
            }, {
                "key": "categorySelector",
                "label": "分类规则",
                "placeholder": ".category",
                "id": "rule-1762074820001-52",
                "value": ""
            }, {
                "key": "introSelector",
                "label": "简介规则",
                "placeholder": ".intro",
                "id": "rule-1762074820001-53",
                "value": ""
            }, {
                "key": "coverSelector",
                "label": "封面规则",
                "placeholder": ".book-cover img::attr(src)",
                "id": "rule-1762074820001-54",
                "value": ""
            }, {
                "key": "detailSelector",
                "label": "详情页地 址规则",
                "placeholder": ".detail-url",
                "id": "rule-1762074820001-55",
                "value": ""
            }, {
                "key": "nextPage",
                "label": "翻页规则",
                "placeholder": "a.next",
                "id": "rule-1762074820001-56",
                "value": ""
            }],
            "detail": [{
                "key": "title",
                "label": "书名规则",
                "placeholder": ".detail-title",
                "id": "rule-1762074820001-57",
                "value": ""
            }, {
                "key": "author",
                "label": "作者规则",
                "placeholder": ".detail-author",
                "id": "rule-1762074820001-58",
                "value": ""
            }, {
                "key": "intro",
                "label": "简介规则",
                "placeholder": ".intro",
                "id": "rule-1762074820001-59",
                "value": ""
            }, {
                "key": "cover",
                "label": "封 面规则",
                "placeholder": ".cover",
                "id": "rule-1762074820001-60",
                "value": ""
            }, {
                "key": "intro",
                "label": "简介规则",
                "placeholder": ".detail-intro",
                "id": "rule-1762074820001-61",
                "value": ""
            }, {
                "key": "dir",
                "label": "目录规则",
                "placeholder": ".list > li",
                "id": "rule-1762074820001-62",
                "value": ""
            }, {
                "key": "latestChapter",
                "label": "最新章节规则",
                "placeholder": ".list > li",
                "id": "rule-1762074820001-63",
                "value": ""
            }, {
                "key": "updateTime",
                "label": "更新时间规则",
                "placeholder": ".update-time",
                "id": "rule-1762074820001-64",
                "value": ""
            }],
            "catalog": [{
                "key": "chapterList",
                "label": "章节列表规则",
                "placeholder": ".chapter-list li",
                "id": "rule-1762074820001-65",
                "value": ""
            }, {
                "key": "chapterTitle",
                "label": "章节标题规则",
                "placeholder": "a",
                "id": "rule-1762074820001-66",
                "value": ""
            }, {
                "key": "chapterUrl",
                "label": "章节链接规则",
                "placeholder": "a::attr(href)",
                "id": "rule-1762074820001-67",
                "value": ""
            }, {
                "key": "updateTime",
                "label": "更新时间规则",
                "placeholder": ".update-time",
                "id": "rule-1762074820001-68",
                "value": ""
            }, {
                "key": "nextPage",
                "label": "翻页规则",
                "placeholder": "a.next",
                "id": "rule-1762074820001-69",
                "value": ""
            }],
            "content": [{
                "key": "content",
                "label": "正文规则",
                "placeholder": ".content",
                "id": "rule-1762074820001-70",
                "value": ""
            }, {
                "key": "filter",
                "label": "内容过滤规则",
                "placeholder": "正则: ^广告 / CSS: .ads",
                "id": "rule-1762074820001-71",
                "value": ""
            }, {
                "key": "image",
                "label": "图片提取规则",
                "placeholder": ".content img::attr(src)",
                "id": "rule-1762074820001-72",
                "value": ""
            }, {
                "key": "nextPage",
                "label": "正文下一页规则",
                "placeholder": "a.next",
                "id": "rule-1762074820001-73",
                "value": ""
            }]
        },
        "createdTime": 1762073104735,
        "updatedTime": 1762073104735
    }
export default demoSource